Styling = 'VCSS' # choices for Styling are 'SCSS' and 'VCSS' (vanilla CSS, albeit nested via PostCSS)
# -- REMINDER:
# -- for 'SCSS' you **must** (a.) load Embedded Dart Sass in the GHA
# -- **or** (b.) use Node Sass and appropriate `package.json` scripting
Nonces = true # Boolean --- 'true' triggers appropriate nonces for Workers/Edge Functions to handle for CSP
SiteLive = 'live' # Boolean --- used for adapting robots.txt as needed
EmailObfuscation = 'local' # choices are 'local' ahd 'host'
Host = 'CFP' # choices are 'CFP' and 'Vercel'
DeepClone = false # Boolean --- Gitinfo from a GHA
# ===========================
Domain = 'brycewray.com'
Author = 'Bryce Wray'
AuthorEmail = 'bw@brycewray.com'
AuthorUrl = 'https://www.brycewray.com/about/'
AuthorAvatar = 'https://www.brycewray.com/images/icons/apple-icon-1024x1024.png'
Description = 'Bryce Wray’s website | Observations, opinions, geekiness'
Site_domain = '{{< Site.Params.Domain >}}'
# https://discourse.gohugo.io/t/site-theme/33200
# -- for /content/posts/2022/05/webmentions-yes-javascript-no-the-code.md
# ===========================
[Titles]
	Contact = 'Want to reach me?'
	Privacy = 'Privacy policy'
	Search = 'Search the site'
	Home = 'Home page'
	Sitemap = 'Sitemap (HTML form)'
	Postslist = 'Posts'
	FourOhFour = '404 Page not found'
	About = 'About me'
# ===========================
