[exec]
	allow = [
		'^(dart-)?sass(-embedded)?$',
		'^go$',
		'^npx$',
		'^postcss$',
		'^subl$',
		'^open$'
	]
[funcs]
	getenv = [
		'^*'
	]
# Sass-related `allow` item from Hugo commit f210188da3ce901d7bdef095c2021f8365bf11e4
# (https://github.com/gohugoio/hugo/commit/f210188da3ce901d7bdef095c2021f8365bf11e4)
