# for Cloudflare Pages

stages:
  - deploy

image: node:latest

variables:
  GITLAB: "false" # make sure the opposite value is set for "GITHUB" in .github/workflows/deploy-hugo-site.yml
  CLOUDFLARE_API_TOKEN: $CFP_API_TOKEN
  CLOUDFLARE_ACCOUNT_ID: $CF_ACCOUNT_ID
  # HUGO_NPM: "true" # choices: 'true' and 'false' (mainly checking only for [== "true"])
  # # ^^ refers to whether we're using the npm pkg `hugo-installer`
  HUGO_VERSION: 0.119.0 # will get Extended Version below
  DART_SASS_VERSION: 1.69.2 # (depends on STYLING var below)
  PAGEFIND_NPM: "true"
  NODE: "true"
  NODE_VERSION: 20.x # (https://developers.cloudflare.com/pages/platform/language-support-and-tools/)
  # ^^ https://developers.cloudflare.com/pages/platform/language-support-and-tools/
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  MY_WEBSITE: https://www.brycewray.com
  PROJECT_NAME: static-site-v2 # was 'static-site'
  STYLING: VCSS # 'SCSS' or 'VCSS'; 'VCSS' requires PostCSS as of 2023-09-04
  TZ: America/Chicago

deploySite:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB == "true"
  environment:
    name: production
    url: $MY_WEBSITE
  script:
    - >
      if [ "$STYLING" == "SCSS" ]; then
        curl -LJO https://github.com/sass/dart-sass/releases/download/${{ env.DART_SASS_VERSION }}/dart-sass-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
        tar -xvf dart-sass-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
        dart-sass/sass --embedded --version
      fi
    - >
      if [ "$NODE" != "true" ]; then
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}
        dpkg -i hugo*.deb
        hugo --gc --minify --logLevel info
        mv public/posts/index.xml public/index-excerpts.xml
        mv public/posts/index.json public/index-excerpts.json
        if [ "$PAGEFIND_NPM" != "true" ]; then
          npm_config_yes=true npx pagefind@latest --site "public"
        fi
      else
        npm install
        npm run build
      fi
    - npm install -g wrangler --unsafe-perm=true
    - wrangler pages deploy ./public --project-name=$PROJECT_NAME --branch "main"
