name: Deploy to web

on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.111.3 # will get Extended Version below (non-Node)
  DART_SASS_VERSION: 1.62.1 # (depends on STYLING env var)
  PAGEFIND_VERSION: 0.12.0 # (non-Node)
  NODE_PKGS: true # choices: 'true' and 'false' (mainly checking only for [== "true"])
  STYLING: VCSS # choices: 'SCSS' and 'VCSS' (VCSS, albeit perhaps with PostCSS for nesting, etc.)
  HOST: CFP # choices: 'CFP' and 'Vercel'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Fetch **all** history (not just deploy commit) for Hugo's .GitInfo and .Lastmod
          # See https://discourse.gohugo.io/t/problems-with-gitinfo-in-ci/22480
      - name: Set up Node.js (cond. - Node)
        if: ${{ env.NODE_PKGS == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install any npm packages (cond. - Node)
        if: ${{ env.NODE_PKGS == 'true' }}
        run: npm install
      - name: Hugo download/install # (cond. - non-Node)
        # if: ${{ env.NODE_PKGS != 'true' }}
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb -O hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
          sudo dpkg -i hugo*.deb
      - name: Install Embedded Dart Sass (cond. - SCSS)
        if: ${{ env.STYLING == 'SCSS' }}
        run: |
          curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${{ env.DART_SASS_VERSION }}/sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
          tar -xvf sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
          sass_embedded/dart-sass-embedded --version
          echo "$GITHUB_WORKSPACE/sass_embedded" >> $GITHUB_PATH
      # # caching suggested by Rodri in https://discord.com/channels/909600839717511208/986399846044958741/1099628644814557185
      # - name: Cache Hugo resources
      #   id: cache-resources
      #   uses: actions/cache@v3
      #   with:
      #     path: resources
      #     key: ${{ runner.os }}-resources
      - name: Install Pagefind # (cond. - non-Node)
        # if: ${{ env.NODE_PKGS != 'true' }}
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/CloudCannon/pagefind/releases/download/v${{ env.PAGEFIND_VERSION }}/pagefind_extended-v${{ env.PAGEFIND_VERSION }}-x86_64-unknown-linux-musl.tar.gz"
          name: "pagefind_extended"
          version: ${{env.PAGEFIND_VERSION}}
      # - name: Build site with Hugo, move feed files, run Pagefind (cond. - Node)
      #   if: ${{ env.NODE_PKGS == 'true' }}
      #   run: npm run build
      - name: Build site with Hugo, move feed files, run Pagefind # (cond. - non-Node)
        # if: ${{ env.NODE_PKGS != 'true' }}
        run: |
          hugo --verbose --minify
          mv public/posts/index.xml public/index-excerpts.xml
          mv public/posts/index.json public/index-excerpts.json
          pagefind_extended --source "public"
      - name: Move Vercel-specific files to `/public` (cond. - host)
        if: ${{ env.HOST == 'Vercel' }}
        run: |
          mv middleware.js public/middleware.js
          mv vercel.json public/vercel.json
      - name: Publish to CFP (cond. - host)
        if: ${{ env.HOST == 'CFP' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CFP_API_TOKEN }}
          accountID: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'static-site'
          directory: 'public'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Vercel (Betahuhn) (cond. - host)
        if: ${{ env.HOST == 'Vercel' }}
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_STATIC_SITE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          WORKING_DIRECTORY: 'public'
      - name: Remove Vercel-specific files from build (cond. - host)
        if: ${{ env.HOST == 'Vercel' }}
        run: |
          rm -rf public/middleware.js
          rm -rf public/vercel.json
# To do a push without triggering this GHA, include one of
# the following in the **commit message**
# (INCLUDING the brackets AND case-sensitivity):
#
# [skip ci]
# [ci skip]
# [no ci]
# [skip actions]
# [actions skip]
#
# “Alternatively, you can end the commit message
# with two empty lines followed by either
# `skip-checks: true` or `skip-checks:true`.”
#
# ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
